export const SITE = {
  website: "https://songtov.github.io/",
  author: "Chiho Song",
  profile: "https://github.com/songtov",
  desc: "AI Engineer 송치호의 개발 노트. AI Agent, LLM, Ontology, 그리고 일하면서 배운 것들.",
  title: "Songtov's Blog",
  ogImage: "astropaper-og.jpg",
  lightAndDarkMode: true,
  postPerIndex: 4,
  postPerPage: 4,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: true,
  showBackButton: true,
  editPost: {
    enabled: true,
    text: "Edit page",
    url: "https://github.com/songtov/songtov.github.io/edit/main/",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "ko",
  timezone: "Asia/Seoul",
} as const;
