export const SITE = {
  website: "https://songtov.github.io/",
  author: "Chiho Song",
  profile: "https://github.com/songtov",
  desc: "AI Engineer Chiho Song의 개발 노트.",
  title: "Songtov's Blog",
  ogImage: "astropaper-og.jpg",
  lightAndDarkMode: true,
  postPerIndex: 4,
  postPerPage: 4,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: true,
  showBackButton: true,
  editPost: {
    enabled: true,
    text: "Edit page",
    url: "https://github.com/songtov/songtov.github.io/edit/main/",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "en",
  timezone: "Asia/Seoul",
} as const;
